stages:
  - pre-prod_build
  - pre-prod_test
  - pre-prod_deploy
  - prod_build
  - prod_test
  - prod_deploy
##======================测试环境=====================
pre-prod_build:
  stage: pre-prod_build
  script:
    - gradle build
  only:
    - /^test-.*$/
  tags:
    - pre-prod
  artifacts:
      paths:
      - target/*.jar


##======================生产环境=====================





