stages:
  - pre-prod_build
  - pre-prod_test
  - pre-prod_deploy
  - prod_build
  - prod_test
  - prod_deploy
##======================测试环境=====================


##======================生产环境=====================





