spring:
  data:
    mongodb:
      host: localhost
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          reactive:
            function: INFO
debug: false
server:
  port: 8080
